<a href="https://colab.research.google.com/github/arunachalamev/PyTorchExperiments/blob/main/TensorFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [13]:
#scalar
scalar = torch.tensor(6)
print (type(scalar), scalar)
print (scalar.ndim)
print (scalar.shape)
scalar.size,scalar.size()

<class 'torch.Tensor'> tensor(6)
0
torch.Size([])


(<function Tensor.size>, torch.Size([]))

In [25]:
# Vector
vector = torch.tensor([1,2])
print (vector.shape)
vector = torch.tensor([[[1],[2]]])
print (vector.shape)
tensor = torch.tensor([[[7,4],[0,1]],[[1,9],[2,3]],[[5,6],[8,8]]])
print (tensor.shape)
tensor


torch.Size([2])
torch.Size([1, 2, 1])
torch.Size([3, 2, 2])


tensor([[[7, 4],
         [0, 1]],

        [[1, 9],
         [2, 3]],

        [[5, 6],
         [8, 8]]])

In [32]:
#Random Tensor
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype, random_tensor.shape, random_tensor.ndim
# random_tensor.shape, random_tensor.size() # both are same

(tensor([[0.8964, 0.5787, 0.5399, 0.6401],
         [0.9514, 0.1996, 0.8382, 0.7077],
         [0.2058, 0.1943, 0.4407, 0.3901]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [38]:
# Zeros, # One
zeros = torch.zeros(size=(3,2,2)) # Tuple or list both accepeted
zeros
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
# range
zero_to_ten = torch.arange(start = 0, end = 10, step= 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# parameters
temp = torch.tensor([3., 6., 9.],
                    dtype = None,
                    device= None,
                    requires_grad=True)
temp

tensor([3., 6., 9.], requires_grad=True)

In [47]:
x = torch.tensor([1,2,3])
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [63]:
x = torch.tensor([[[1],[1]],[[2],[2]],[[3],[3]]])
x
x.squeeze().shape
y = torch.rand(size=(3,2,1))
print(y)
y.squeeze()

tensor([[[0.8090],
         [0.8995]],

        [[0.0149],
         [0.3460]],

        [[0.7858],
         [0.7371]]])


tensor([[0.8090, 0.8995],
        [0.0149, 0.3460],
        [0.7858, 0.7371]])

In [ ]:
# print (torch.__version__)
a = torch.tensor(3) 
b = torch.tensor([3.])
c = torch.tensor([1,2,3])
d = torch.tensor([[1,2,3],[3,4,5]])
e = torch.rand(size=(10,10,3,5,4))
g = torch.ones(size=(2,1,4), dtype=torch.int8, device = None, requires_grad=False)

a
print (a.ndim, a.shape)
print (b.ndim, b.shape)
print (c.ndim,c.shape)
print (d.ndim,d.shape)
print (e.ndim,e.shape)
print (g.ndim, g.shape)
g+10


# Common errors - Datatype, shape and device 

0 torch.Size([])
1 torch.Size([1])
1 torch.Size([3])
2 torch.Size([2, 3])
5 torch.Size([10, 10, 3, 5, 4])
3 torch.Size([2, 1, 4])


tensor([[[11, 11, 11, 11]],

        [[11, 11, 11, 11]]], dtype=torch.int8)

In [ ]:
# Matris Multiplication
# Element wise and Matrix multiplication ( dot product)

temp = torch.tensor([1,2,3])
# Elementwise multiplication
temp * temp
print (temp.mul(temp))

# Matrix Multiplication
print (temp.matmul(temp)) # dot product
print (torch.matmul(temp,temp))

tensor([1, 4, 9])
tensor(14)
tensor(14)


In [ ]:
%%time
value = 0
for i in range(len(temp)):
  value += temp[i]*temp[i]
print (value)

tensor(14)
CPU times: user 2.85 ms, sys: 51 µs, total: 2.9 ms
Wall time: 3.03 ms


In [ ]:
%%time
# print (temp.matmul(temp))
torch.matmul(temp,temp)
# print (temp)

CPU times: user 281 µs, sys: 887 µs, total: 1.17 ms
Wall time: 1.11 ms


tensor(14)

In [ ]:
temp @ temp # similar to matmul. Prefer matmul

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

#Matrix multiplication rules - Inner dimensions match , result is the outer dimension

tensor([[0.6199, 0.6723, 0.6093],
        [0.4771, 0.9395, 0.7847],
        [0.3637, 0.7140, 0.5965]])

In [ ]:
Tensor_A = torch.rand(3,2)
Tensor_B = torch.rand(3,2)

In [ ]:
torch.matmul(Tensor_A,Tensor_B)

RuntimeError: ignored

In [ ]:
torch.matmul(Tensor_A,Tensor_B.T) # transpose to match the dimension using reshaping

tensor([[0.2957, 0.5822, 1.0903],
        [0.1257, 0.2236, 0.4693],
        [0.2189, 0.3924, 0.8165]])