<a href="https://colab.research.google.com/github/arunachalamev/PyTorchExperiments/blob/main/TensorFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [32]:
# print (torch.__version__)
a = torch.tensor(3)
b = torch.tensor([3.])
c = torch.tensor([1,2,3])
d = torch.tensor([[1,2,3],[3,4,5]])
e = torch.rand(size=(10,10,3,5,4))
g = torch.ones(size=(2,1,4), dtype=torch.int8, device = None, requires_grad=False)

a
print (a.ndim, a.shape)
print (b.ndim, b.shape)
print (c.ndim,c.shape)
print (d.ndim,d.shape)
print (e.ndim,e.shape)
print (g.ndim, g.shape)
g+10


# Common errors - Datatype, shape and device 

0 torch.Size([])
1 torch.Size([1])
1 torch.Size([3])
2 torch.Size([2, 3])
5 torch.Size([10, 10, 3, 5, 4])
3 torch.Size([2, 1, 4])


tensor([[[11, 11, 11, 11]],

        [[11, 11, 11, 11]]], dtype=torch.int8)

In [42]:
# Matris Multiplication
# Element wise and Matrix multiplication ( dot product)

temp = torch.tensor([1,2,3])
# Elementwise multiplication
temp * temp
print (temp.mul(temp))

# Matrix Multiplication
print (temp.matmul(temp)) # dot product
print (torch.matmul(temp,temp))

tensor([1, 4, 9])
tensor(14)
tensor(14)


In [40]:
%%time
value = 0
for i in range(len(temp)):
  value += temp[i]*temp[i]
print (value)

tensor(14)
CPU times: user 2.85 ms, sys: 51 µs, total: 2.9 ms
Wall time: 3.03 ms


In [52]:
%%time
# print (temp.matmul(temp))
torch.matmul(temp,temp)
# print (temp)

CPU times: user 281 µs, sys: 887 µs, total: 1.17 ms
Wall time: 1.11 ms


tensor(14)

In [53]:
temp @ temp # similar to matmul. Prefer matmul

tensor(14)

In [54]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

#Matrix multiplication rules - Inner dimensions match , result is the outer dimension

tensor([[0.6199, 0.6723, 0.6093],
        [0.4771, 0.9395, 0.7847],
        [0.3637, 0.7140, 0.5965]])

In [57]:
Tensor_A = torch.rand(3,2)
Tensor_B = torch.rand(3,2)

In [58]:
torch.matmul(Tensor_A,Tensor_B)

RuntimeError: ignored

In [59]:
torch.matmul(Tensor_A,Tensor_B.T) # transpose to match the dimension using reshaping

tensor([[0.2957, 0.5822, 1.0903],
        [0.1257, 0.2236, 0.4693],
        [0.2189, 0.3924, 0.8165]])